
MODULE_LD_FOOTER := $(TEMPLATES_DIR)module.footer.ld
MODULE_LINKSCRIPT := $(BUILD_DIR)module.ld

$(MODULE_LINKSCRIPT): $(KERNEL_BIN) $(MODLDGEN_BIN) $(MODULE_LD_FOOTER)
	$(MODLDGEN_BIN) $(KERNEL_SYM) $@ $(MODULE_LD_FOOTER)

.PHONY: modld
modld: $(MODULE_LINKSCRIPT)

CLEAN += $(INITRD_SYSROOT)modules/

MODULES_ALL :=
