#!/bin/bash

bg_black=$(  tput setab 0 )
bg_red=$(    tput setab 1 )
bg_green=$(  tput setab 2 )
bg_yellow=$( tput setab 3 )
bg_blue=$(   tput setab 4 )
bg_magenta=$(tput setab 5 )
bg_cyan=$(   tput setab 6 )
bg_white=$(  tput setab 7 )

fg_bLack=$(  tput setaf 0 )
fg_red=$(    tput setaf 1 )
fg_green=$(  tput setaf 2 )
fg_yellow=$( tput setaf 3 )
fg_blue=$(   tput setaf 4 )
fg_magenta=$(tput setaf 5 )
fg_cyan=$(   tput setaf 6 )
fg_white=$(  tput setaf 7 )

bold=$(          tput bold)
half=$(          tput dim )
underline=$(     tput smul)
end_underline=$( tput rmul)
reverse=$(       tput rev )
standout=$(      tput smso)
end_stand_out=$( tput rmso)
reset=$(         tput sgr0)